### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by roxaloxa** [Native-Coder/node-bungie-lib#16]
Hello! I'm writing a Destiny 2 site and was wondering if this library was still being worked on. I've been using another one and I'm not too thrilled with it so far, but I don't want to jump ship quite yet until I know this one is at least getting some attention. 😅 I also would likely try and contribute to the project where I could while I was building my site out.

**Comment by Native-Coder** [comment]
I'm taking a semseter off of school so I'll have time to give this project some attention. I'll definately keep an eye out of PRs. thanks for the question.
